source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Our Libraries
def libraries
  pod 'Moya-ObjectMapper/ReactiveSwift', :path => "../"
  pod 'Moya', '11.0.0-beta.2'
end

# Test Libraries
def test_pods
  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs'
end

target 'Demo' do
  platform :ios, '9.0'
  libraries
end
